import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/_components/header";
import { Footer } from "@/_components/footer";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: 'SWETOUR - A guide to cities in Sweden',
    template: '%s | SWETOUR',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen grid grid-rows-[auto_1fr_auto]`}
      >
        <Header />
        {/* <ErrorWrapper> */}
          {children}
        {/* </ErrorWrapper> */}
        <Footer />
      </body>
    </html>
  );
}
